#!/usr/bin/env tsx
/**
 * Generate Supabase TypeScript types from your remote project
 * 
 * Usage:
 *   Option 1: From remote project (recommended)
 *     SUPABASE_PROJECT_ID=your-project-id npm run generate:types
 *     OR
 *     npx supabase gen types typescript --project-id your-project-id > src/lib/supabase/types-generated.ts
 * 
 *   Option 2: From local database (if running)
 *     npx supabase gen types typescript --local > src/lib/supabase/types-generated.ts
 * 
 * After generation, replace src/lib/supabase/types.ts with the generated file.
 */

import { execSync } from 'child_process';
import { writeFileSync } from 'fs';
import { join } from 'path';
import { config } from 'dotenv';
import { resolve } from 'path';

// Load .env.local if it exists
config({ path: resolve(process.cwd(), '.env.local') });

// Try to get project ID from env variable first
let projectId = process.env.SUPABASE_PROJECT_ID;

// If not set, try to extract from NEXT_PUBLIC_SUPABASE_URL
if (!projectId) {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  if (supabaseUrl) {
    // Supabase URL format: https://xxxxx.supabase.co
    // Extract the project reference ID (the part before .supabase.co)
    const match = supabaseUrl.match(/https?:\/\/([^.]+)\.supabase\.co/);
    if (match && match[1]) {
      projectId = match[1];
      console.log(`📋 Extracted project ID from NEXT_PUBLIC_SUPABASE_URL: ${projectId}`);
    }
  }
}

const outputPath = join(process.cwd(), 'src/lib/supabase/types-generated.ts');

if (!projectId) {
  console.error(`
❌ Could not find Supabase Project ID.

Tried to find it from:
  - SUPABASE_PROJECT_ID environment variable
  - NEXT_PUBLIC_SUPABASE_URL (extracting from URL)

To generate types from your remote Supabase project:

1. Get your project ID from Supabase Dashboard:
   https://supabase.com/dashboard/project/_/settings/general
   (It's the "Reference ID" in the project settings)

2. Run one of these commands:
   
   Option A: Set env variable and run script
     SUPABASE_PROJECT_ID=your-project-id npm run generate:types
   
   Option B: Use Supabase CLI directly
     npx supabase gen types typescript --project-id your-project-id > src/lib/supabase/types-generated.ts

3. After generation, replace src/lib/supabase/types.ts with types-generated.ts
`);
  process.exit(1);
}

try {
  console.log(`🔄 Generating types from project: ${projectId}...`);
  
  const types = execSync(
    `npx supabase gen types typescript --project-id ${projectId}`,
    { encoding: 'utf-8', stdio: 'pipe' }
  );

  // Add header comment
  const header = `// This file is auto-generated by Supabase CLI.
// To regenerate: npm run generate:types
// DO NOT EDIT MANUALLY - your changes will be overwritten.

`;

  writeFileSync(outputPath, header + types);
  
  console.log(`✅ Types generated successfully at: ${outputPath}`);
  console.log(`\n📝 Next steps:`);
  console.log(`   1. Review the generated types in ${outputPath}`);
  console.log(`   2. Replace src/lib/supabase/types.ts with the generated file`);
  console.log(`   3. Update imports if needed (the structure should be the same)`);
  
} catch (error) {
  console.error('❌ Failed to generate types:', error);
  console.error('\n💡 Make sure you are logged in to Supabase CLI:');
  console.error('   npx supabase login');
  process.exit(1);
}
