"use client";

import { useEffect, useRef, useState } from "react";
import { NextIntlClientProvider } from "next-intl";
import messages from "../../../../messages/en.json";
import AuthorAppShell from "@/features/author-shell/AuthorAppShell";
import AgentCompanion from "@/features/ai-team/AgentCompanion";
import AudiobookPanel from "../../(app-author)/author/books/[id]/editor/panels/AudiobookPanel";
import type { AudiobookGenerationScope, Chapter } from "../../(app-author)/author/books/[id]/editor/BookEditorView.types";

const CHAPTERS: Chapter[] = ["The harbour", "A letter from home", "The last crossing"].map((title, index) => ({ id: `sample-${index}`, title, order: index, book_version_id: "sample-edition", content: "The rain was falling over the quiet harbour. ".repeat(180) }));
const STATES = ["ready", "empty", "generating", "paused", "failed", "completed", "payment", "billing-loading", "disabled", "preview-error", "playback-error"] as const;
type PreviewState = typeof STATES[number];

/** A local test tone, never generated by or sent to an audio provider. */
function sampleAudio() {
  const rate = 8000;
  const samples = rate * 3;
  const buffer = new ArrayBuffer(44 + samples * 2);
  const view = new DataView(buffer);
  const text = (offset: number, value: string) => [...value].forEach((char, index) => view.setUint8(offset + index, char.charCodeAt(0)));
  text(0, "RIFF"); view.setUint32(4, 36 + samples * 2, true); text(8, "WAVE"); text(12, "fmt "); view.setUint32(16, 16, true); view.setUint16(20, 1, true); view.setUint16(22, 1, true); view.setUint32(24, rate, true); view.setUint32(28, rate * 2, true); view.setUint16(32, 2, true); view.setUint16(34, 16, true); text(36, "data"); view.setUint32(40, samples * 2, true);
  for (let i = 0; i < samples; i++) view.setInt16(44 + i * 2, Math.sin(i / rate * 220 * Math.PI * 2) * 1500, true);
  return new Blob([buffer], { type: "audio/wav" });
}

export default function AudiobookPreview() {
  const [ready, setReady] = useState(false);
  const [state, setState] = useState<PreviewState>("ready");
  const stateRef = useRef(state);
  const [language, setLanguage] = useState("en");
  const [scope, setScope] = useState<AudiobookGenerationScope>("book");
  const [selected, setSelected] = useState<string[]>([]);
  const [picker, setPicker] = useState(false);
  const [checkout, setCheckout] = useState(false);
  const [paying, setPaying] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState("");
  const [audioUrl, setAudioUrl] = useState<string | null>(null);
  const [brokenUrl, setBrokenUrl] = useState<string | null>(null);
  useEffect(() => { stateRef.current = state; }, [state]);
  useEffect(() => {
    const originalFetch = window.fetch;
    const sample = sampleAudio();
    const url = URL.createObjectURL(sample);
    const broken = URL.createObjectURL(new Blob(["Invalid audio fixture"], { type: "audio/wav" }));
    window.fetch = async (input, init) => {
      const target = new URL(input instanceof Request ? input.url : String(input), location.origin);
      const method = (init?.method ?? (input instanceof Request ? input.method : "GET")).toUpperCase();
      if (target.pathname === "/api/books/audio-preview-only/audiobook/preview") {
        await new Promise((resolve) => setTimeout(resolve, 700));
        return stateRef.current === "preview-error" ? Response.json({ detail: "Preview could not be created. Please try again." }, { status: 503 }) : new Response(sample);
      }
      if (method !== "GET" && method !== "HEAD") return Response.json({ error: "PREVIEW_ONLY" }, { status: 403 });
      if (target.pathname === "/api/notifications/unread-count") return Response.json({ count: 0 });
      if (target.pathname === "/api/notifications") return Response.json({ notifications: [], total: 0 });
      if (target.pathname === "/rest/v1/books") return Response.json([]);
      if (target.origin !== location.origin || target.pathname.startsWith("/api/")) return Response.json({ error: "PREVIEW_ONLY" }, { status: 403 });
      return originalFetch(input, init);
    };
    const preventWrite = (event: Event) => { if (event.target instanceof HTMLFormElement && event.target.method.toLowerCase() !== "get") event.preventDefault(); };
    document.addEventListener("submit", preventWrite, true);
    const timer = window.setTimeout(() => { setAudioUrl(url); setBrokenUrl(broken); setReady(true); }, 0);
    return () => { window.clearTimeout(timer); window.fetch = originalFetch; URL.revokeObjectURL(url); URL.revokeObjectURL(broken); document.removeEventListener("submit", preventWrite, true); };
  }, []);
  const chapters = state === "empty" ? [] : CHAPTERS.map((chapter) => ({ ...chapter, book_version_id: `sample-edition-${language}` }));
  const active = state === "generating" || state === "paused";
  const requested = scope === "book" ? chapters.map((chapter) => chapter.id) : scope === "current" ? ["sample-1"] : selected;
  return <>
    <section aria-label="Audiobook preview controls" className="flex flex-wrap items-center gap-4 border-b border-border bg-muted px-4 py-2 text-xs">
      <label className="flex min-h-11 items-center gap-2">Preview state<select className="min-h-11 rounded border border-border bg-background px-2" value={state} onChange={(event) => { setState(event.target.value as PreviewState); setError(null); setCheckout(false); }}>
        {STATES.map((value) => <option key={value}>{value}</option>)}
      </select></label>
      <label className="flex min-h-11 items-center gap-2">Selected edition<select className="min-h-11 rounded border border-border bg-background px-2" value={language} onChange={(event) => setLanguage(event.target.value)}>
        <option value="en">English · older edition</option><option value="sv">Swedish · newer edition</option>
      </select></label>
      <button className="min-h-11 px-3" onClick={() => document.documentElement.classList.toggle("dark")}>Toggle theme</button>
      <p>Synthetic manuscript · local test tone · no generation, payments or saved changes</p>
      {message && <p role="status">{message}</p>}
    </section>
    {ready ? <NextIntlClientProvider locale="en" messages={messages}><AuthorAppShell>
      <div className="border-b border-border px-6 py-5 text-sm text-muted-foreground">Library <span className="mx-2">/</span> Den sista färjan <span className="mx-2">/</span> Audio</div>
      <div className="mx-auto max-w-[1320px] px-4 py-6 sm:px-8 lg:px-10">
        <AgentCompanion agent="august" onTalk={() => setMessage("August connection selected. This local fixture does not send chat messages.")} />
        <AudiobookPanel key={state} bookId="audio-preview-only" bookLanguage="en" bookOriginalLanguage="en" chapters={chapters} selectedChapterId="sample-1" activeVersion={{ id: `sample-edition-${language}`, book_id: "audio-preview-only", language_code: language, status: "draft" }} activeLanguage={language} totalBookWordCount={chapters.length * 1440}
          billingLoading={state === "billing-loading"} billingIsProActive={state !== "payment"} audiobookFeatureEnabled={state !== "disabled"} isAudiobookActive={active} audiobookStatusUi={state === "generating" ? "generating" : state === "paused" ? "paused" : state === "failed" ? "failed" : state === "completed" ? "completed" : "idle"}
          audiobookError={error} effectiveAudiobookError={state === "failed" ? "Generation stopped at chapter 2. Please try again." : null} effectiveAudiobookProgress={active ? { totalChapters: 3, completedChapters: 1, currentChapterTitle: "A letter from home", estimatedSecondsRemaining: 120 } : null} audiobookEtaText={active ? "About 2 minutes remaining" : null}
          audiobookScope={scope} setAudiobookScope={setScope} audiobookSelectedChapterIds={selected} setAudiobookSelectedChapterIds={setSelected} isAudiobookChapterPickerOpen={picker} setIsAudiobookChapterPickerOpen={setPicker} audiobookRequestedChapterIds={requested} audiobookControlPending={null} canPauseAudiobook={state === "generating"} canResumeAudiobook={state === "paused"} canCancelAudiobook={active}
          handleAudiobookControl={async (action) => { setState(action === "pause" ? "paused" : action === "resume" ? "generating" : "ready"); setMessage(`Local generation ${action}.`); }} handleGenerateAudiobook={async () => { if (state === "payment") setCheckout(true); else setState("generating"); }} audiobookSelectedLanguages={["en"]} setAudiobookSelectedLanguages={() => {}}
          audiobookCheckoutModalOpen={checkout} setAudiobookCheckoutModalOpen={setCheckout} audiobookCheckoutLoading={paying} handleAudiobookCheckout={async () => { setPaying(true); setError(null); await new Promise((resolve) => setTimeout(resolve, 600)); setPaying(false); setError("Checkout could not be opened. Nothing was charged. Please try again."); }} shouldShowGeneratedAudiobookPlayer={state === "completed" || state === "playback-error"} fallbackGeneratedAudiobookUrl={state === "playback-error" ? brokenUrl : audioUrl} latestAudiobookManifestUrl={null}
        />
      </div>
    </AuthorAppShell></NextIntlClientProvider> : <p className="p-6" role="status">Preparing local audiobook preview…</p>}
  </>;
}
