"use client";
import { useEffect, useRef, useState } from "react";
import { useTrailerWizard } from "@/components/marketing/wizard/WizardContext";
const BUILDING_LABELS = ["Genererar scener...", "Sätter ihop video...", "Laddar upp..."];
export default function StepBuildTrailer() {
  const { state, canGoBack, goBack, fetchQuota, buildTrailer, resetBuild } = useTrailerWizard();
  const hasFetchedQuota = useRef(false);
  const [buildLabelIndex, setBuildLabelIndex] = useState(0);
  useEffect(() => { if ((state.build.status === "idle" || state.build.status === "fetching_quota") && !hasFetchedQuota.current) { hasFetchedQuota.current = true; void fetchQuota(); } }, [state.build.status, fetchQuota]);
  useEffect(() => { if (state.build.status !== "building") return; const interval = setInterval(() => { setBuildLabelIndex((prev) => (prev + 1) % BUILDING_LABELS.length); }, 4000); return () => clearInterval(interval); }, [state.build.status]);
  const isBuilding = state.build.status === "building";
  const isCompleted = state.build.status === "completed";
  const isError = state.build.status === "error";
  const isConfirming = state.build.status === "confirming" || state.build.status === "fetching_quota";
  const canBuild = state.build.isProUser && state.build.quotaUsed < state.build.quotaLimit && !isBuilding;
  function handleCopyCaption() { if (state.build.caption) void navigator.clipboard.writeText(state.build.caption); }
  if (isConfirming) return (<section className="space-y-4"><div className="card-base p-5"><h2 className="text-[15px] font-semibold text-slate-900 dark:text-white">Skapa trailer</h2><p className="mt-1 text-[13px] text-slate-500 dark:text-white/50">Granska din kvot och bygg din färdiga boktrailer.</p><div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-4 dark:border-white/10 dark:bg-white/[0.03]"><div className="flex items-center justify-between"><span className="text-[12px] text-slate-500 dark:text-white/50">Använt denna månad</span><span className="rounded-full border border-slate-200 bg-white px-2.5 py-0.5 text-[12px] font-medium text-slate-700 dark:border-white/15 dark:bg-white/5 dark:text-white/70">{state.build.isProUser ? "Pro" : "Free"}</span></div><p className="mt-1 text-[18px] font-semibold text-slate-900 dark:text-white">{state.build.quotaUsed} / {state.build.quotaLimit}</p></div>{state.build.isProUser ? <button type="button" onClick={() => void buildTrailer()} disabled={!canBuild} className="btn-primary mt-4 w-full disabled:cursor-not-allowed disabled:opacity-60">{state.build.quotaUsed >= state.build.quotaLimit ? "Kvoten uppnådd" : "Skapa trailer"}</button> : <a href="/author/billing" className="btn-primary mt-4 block w-full text-center">Uppgradera för att bygga</a>}</div><div className="flex justify-start"><button type="button" onClick={goBack} disabled={!canGoBack} className="rounded-xl border border-slate-200 px-4 py-2 text-[13px] font-semibold text-slate-700 transition hover:border-slate-300 disabled:cursor-not-allowed disabled:opacity-60 dark:border-white/20 dark:text-white/80 dark:hover:border-white/30">Tillbaka</button></div></section>);
  if (isBuilding) return (<section className="space-y-4"><div className="card-base flex flex-col items-center p-8"><div className="h-12 w-12 animate-spin rounded-full border-4 border-slate-200 border-t-slate-900 dark:border-white/10 dark:border-t-white" /><p className="mt-4 text-[14px] font-semibold text-slate-900 dark:text-white">{BUILDING_LABELS[buildLabelIndex]}</p><p className="mt-1 text-[12px] text-slate-500 dark:text-white/50">ca 2-3 minuter</p><p className="mt-3 text-[12px] text-slate-400 dark:text-white/30">Du kan lämna sidan - trailern fortsätter att byggas.</p></div></section>);
  if (isCompleted) return (<section className="space-y-4"><div className="card-base p-5"><h2 className="text-[15px] font-semibold text-slate-900 dark:text-white">Din trailer är klar!</h2>{state.build.videoUrl && <div className="mt-4 overflow-hidden rounded-xl border border-slate-200 dark:border-white/10"><video src={state.build.videoUrl} controls autoPlay muted playsInline className="h-auto w-full bg-black" /></div>}{state.build.caption && <div className="mt-4"><label className="mb-1.5 block text-[12px] font-medium text-slate-600 dark:text-white/60">Caption</label><div className="relative"><textarea className="input-base min-h-[80px] resize-y" value={state.build.caption} readOnly /><button type="button" onClick={handleCopyCaption} className="absolute right-2 top-2 rounded-lg border border-slate-200 bg-white px-2 py-1 text-[11px] font-medium text-slate-600 transition hover:border-slate-300 dark:border-white/20 dark:bg-white/5 dark:text-white/70 dark:hover:border-white/30">Kopiera</button></div></div>}{state.generate.hashtags.length > 0 && <div className="mt-3 flex flex-wrap gap-1.5">{state.generate.hashtags.map((tag) => <span key={tag} className="rounded-full border border-slate-200 bg-slate-50 px-2 py-0.5 text-[11px] text-slate-500 dark:border-white/15 dark:bg-white/5 dark:text-white/50">{tag}</span>)}</div>}{state.build.videoUrl && <a href={state.build.videoUrl} download className="mt-4 inline-block rounded-xl border border-slate-200 px-4 py-2 text-[13px] font-semibold text-slate-700 transition hover:border-slate-300 dark:border-white/20 dark:text-white/80 dark:hover:border-white/30">Ladda ner</a>}</div><button type="button" onClick={resetBuild} className="rounded-xl border border-slate-200 px-4 py-2 text-[13px] font-semibold text-slate-700 transition hover:border-slate-300 dark:border-white/20 dark:text-white/80 dark:hover:border-white/30">Skapa en ny version</button></section>);
  if (isError) return (<section className="space-y-4"><div className="card-base border-red-200 bg-red-50 p-5 dark:border-red-500/40 dark:bg-red-950/20"><p className="text-[13px] font-semibold text-red-700 dark:text-red-300">Kunde inte bygga trailern</p><p className="mt-1 text-[12px] text-red-600 dark:text-red-400">{state.build.errorMessage}</p><button type="button" onClick={() => void buildTrailer()} className="btn-primary mt-3">Försök igen</button></div><div className="flex justify-start"><button type="button" onClick={goBack} disabled={!canGoBack} className="rounded-xl border border-slate-200 px-4 py-2 text-[13px] font-semibold text-slate-700 transition hover:border-slate-300 disabled:cursor-not-allowed disabled:opacity-60 dark:border-white/20 dark:text-white/80 dark:hover:border-white/30">Tillbaka</button></div></section>);
  return (<section className="card-base p-5 text-center"><p className="text-[13px] text-slate-500 dark:text-white/50">Laddar...</p></section>);
}
