// This file is auto-generated by Supabase CLI.
// To regenerate: npm run generate:types
// DO NOT EDIT MANUALLY - your changes will be overwritten.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.1"
  }
  public: {
    Tables: {
      ai_jobs: {
        Row: {
          created_at: string
          error: string | null
          finished_at: string | null
          id: string
          input: Json | null
          kind: string
          output: Json | null
          started_at: string | null
          status: string
          user_id: string
        }
        Insert: {
          created_at?: string
          error?: string | null
          finished_at?: string | null
          id?: string
          input?: Json | null
          kind: string
          output?: Json | null
          started_at?: string | null
          status?: string
          user_id: string
        }
        Update: {
          created_at?: string
          error?: string | null
          finished_at?: string | null
          id?: string
          input?: Json | null
          kind?: string
          output?: Json | null
          started_at?: string | null
          status?: string
          user_id?: string
        }
        Relationships: []
      }
      analytics_events: {
        Row: {
          anon_id: string | null
          created_at: string
          event_name: string
          id: string
          ip_hash: string | null
          path: string | null
          props: Json
          referrer: string | null
          role: string | null
          session_id: string | null
          user_agent: string | null
          user_id: string | null
        }
        Insert: {
          anon_id?: string | null
          created_at?: string
          event_name: string
          id?: string
          ip_hash?: string | null
          path?: string | null
          props?: Json
          referrer?: string | null
          role?: string | null
          session_id?: string | null
          user_agent?: string | null
          user_id?: string | null
        }
        Update: {
          anon_id?: string | null
          created_at?: string
          event_name?: string
          id?: string
          ip_hash?: string | null
          path?: string | null
          props?: Json
          referrer?: string | null
          role?: string | null
          session_id?: string | null
          user_agent?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      audiobook_assets: {
        Row: {
          audio_url: string | null
          book_id: string
          created_at: string
          duration_seconds: number | null
          id: string
          language: string
          status: string
        }
        Insert: {
          audio_url?: string | null
          book_id: string
          created_at?: string
          duration_seconds?: number | null
          id?: string
          language?: string
          status?: string
        }
        Update: {
          audio_url?: string | null
          book_id?: string
          created_at?: string
          duration_seconds?: number | null
          id?: string
          language?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "audiobook_assets_book_id_fkey"
            columns: ["book_id"]
            isOneToOne: false
            referencedRelation: "books"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_log: {
        Row: {
          action: string
          actor_role: string | null
          actor_user_id: string | null
          created_at: string
          entity_id: string | null
          entity_type: string
          id: string
          meta: Json
          request_id: string | null
        }
        Insert: {
          action: string
          actor_role?: string | null
          actor_user_id?: string | null
          created_at?: string
          entity_id?: string | null
          entity_type: string
          id?: string
          meta?: Json
          request_id?: string | null
        }
        Update: {
          action?: string
          actor_role?: string | null
          actor_user_id?: string | null
          created_at?: string
          entity_id?: string | null
          entity_type?: string
          id?: string
          meta?: Json
          request_id?: string | null
        }
        Relationships: []
      }
      billing_customers: {
        Row: {
          created_at: string
          stripe_customer_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          stripe_customer_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          stripe_customer_id?: string
          user_id?: string
        }
        Relationships: []
      }
      billing_subscriptions: {
        Row: {
          cancel_at_period_end: boolean
          created_at: string
          current_period_end: string | null
          id: string
          price_id: string | null
          status: string
          stripe_subscription_id: string
          updated_at: string
          user_id: string
        }
        Insert: {
          cancel_at_period_end?: boolean
          created_at?: string
          current_period_end?: string | null
          id?: string
          price_id?: string | null
          status: string
          stripe_subscription_id: string
          updated_at?: string
          user_id: string
        }
        Update: {
          cancel_at_period_end?: boolean
          created_at?: string
          current_period_end?: string | null
          id?: string
          price_id?: string | null
          status?: string
          stripe_subscription_id?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      book_imports: {
        Row: {
          author_id: string
          book_id: string | null
          book_version_id: string | null
          created_at: string
          error_message: string | null
          file_name: string
          file_path: string
          file_storage: string
          id: string
          progress: number
          status: string
          updated_at: string
        }
        Insert: {
          author_id: string
          book_id?: string | null
          book_version_id?: string | null
          created_at?: string
          error_message?: string | null
          file_name: string
          file_path: string
          file_storage?: string
          id?: string
          progress?: number
          status?: string
          updated_at?: string
        }
        Update: {
          author_id?: string
          book_id?: string | null
          book_version_id?: string | null
          created_at?: string
          error_message?: string | null
          file_name?: string
          file_path?: string
          file_storage?: string
          id?: string
          progress?: number
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "book_imports_book_id_fkey"
            columns: ["book_id"]
            isOneToOne: false
            referencedRelation: "books"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "book_imports_book_version_id_fkey"
            columns: ["book_version_id"]
            isOneToOne: false
            referencedRelation: "book_versions"
            referencedColumns: ["id"]
          },
        ]
      }
      book_versions: {
        Row: {
          book_id: string
          created_at: string
          id: string
          language_code: string
          published_at: string | null
          status: string
          updated_at: string
        }
        Insert: {
          book_id: string
          created_at?: string
          id?: string
          language_code: string
          published_at?: string | null
          status?: string
          updated_at?: string
        }
        Update: {
          book_id?: string
          created_at?: string
          id?: string
          language_code?: string
          published_at?: string | null
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "book_versions_book_id_fkey"
            columns: ["book_id"]
            isOneToOne: false
            referencedRelation: "books"
            referencedColumns: ["id"]
          },
        ]
      }
      bookmarks: {
        Row: {
          book_id: string
          created_at: string
          id: string
          user_id: string
        }
        Insert: {
          book_id: string
          created_at?: string
          id?: string
          user_id: string
        }
        Update: {
          book_id?: string
          created_at?: string
          id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "bookmarks_book_id_fkey"
            columns: ["book_id"]
            isOneToOne: false
            referencedRelation: "books"
            referencedColumns: ["id"]
          },
        ]
      }
      books: {
        Row: {
          audiobook_status: string | null
          author_id: string
          cover_image: string | null
          created_at: string
          description: string | null
          featured: boolean | null
          featured_rank: number | null
          featured_until: string | null
          id: string
          is_featured: boolean
          is_translation: boolean
          language: string | null
          original_book_id: string | null
          original_language: string | null
          original_source: string | null
          original_url: string | null
          published: boolean
          published_at: string | null
          slug: string
          status: Database["public"]["Enums"]["book_status"]
          title: string
          translation_status: string | null
          updated_at: string
        }
        Insert: {
          audiobook_status?: string | null
          author_id: string
          cover_image?: string | null
          created_at?: string
          description?: string | null
          featured?: boolean | null
          featured_rank?: number | null
          featured_until?: string | null
          id?: string
          is_featured?: boolean
          is_translation?: boolean
          language?: string | null
          original_book_id?: string | null
          original_language?: string | null
          original_source?: string | null
          original_url?: string | null
          published?: boolean
          published_at?: string | null
          slug: string
          status?: Database["public"]["Enums"]["book_status"]
          title: string
          translation_status?: string | null
          updated_at?: string
        }
        Update: {
          audiobook_status?: string | null
          author_id?: string
          cover_image?: string | null
          created_at?: string
          description?: string | null
          featured?: boolean | null
          featured_rank?: number | null
          featured_until?: string | null
          id?: string
          is_featured?: boolean
          is_translation?: boolean
          language?: string | null
          original_book_id?: string | null
          original_language?: string | null
          original_source?: string | null
          original_url?: string | null
          published?: boolean
          published_at?: string | null
          slug?: string
          status?: Database["public"]["Enums"]["book_status"]
          title?: string
          translation_status?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "books_original_book_id_fkey"
            columns: ["original_book_id"]
            isOneToOne: false
            referencedRelation: "books"
            referencedColumns: ["id"]
          },
        ]
      }
      chapters: {
        Row: {
          book_id: string
          book_version_id: string
          content: string
          content_hash: string | null
          created_at: string
          id: string
          order: number
          source_text: string | null
          title: string
          updated_at: string
        }
        Insert: {
          book_id: string
          book_version_id: string
          content?: string
          content_hash?: string | null
          created_at?: string
          id?: string
          order: number
          source_text?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          book_id?: string
          book_version_id?: string
          content?: string
          content_hash?: string | null
          created_at?: string
          id?: string
          order?: number
          source_text?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "chapters_book_id_fkey"
            columns: ["book_id"]
            isOneToOne: false
            referencedRelation: "books"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "chapters_book_version_id_fkey"
            columns: ["book_version_id"]
            isOneToOne: false
            referencedRelation: "book_versions"
            referencedColumns: ["id"]
          },
        ]
      }
      curated_list_items: {
        Row: {
          book_id: string
          created_at: string
          id: string
          list_id: string
          rank: number
        }
        Insert: {
          book_id: string
          created_at?: string
          id?: string
          list_id: string
          rank?: number
        }
        Update: {
          book_id?: string
          created_at?: string
          id?: string
          list_id?: string
          rank?: number
        }
        Relationships: [
          {
            foreignKeyName: "curated_list_items_book_id_fkey"
            columns: ["book_id"]
            isOneToOne: false
            referencedRelation: "books"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "curated_list_items_list_id_fkey"
            columns: ["list_id"]
            isOneToOne: false
            referencedRelation: "curated_lists"
            referencedColumns: ["id"]
          },
        ]
      }
      curated_lists: {
        Row: {
          created_at: string
          description: string | null
          id: string
          is_active: boolean
          language: string
          slug: string
          title: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          is_active?: boolean
          language?: string
          slug: string
          title: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          is_active?: boolean
          language?: string
          slug?: string
          title?: string
        }
        Relationships: []
      }
      feedback: {
        Row: {
          created_at: string
          id: string
          message: string
          request_id: string | null
          status: string
          type: string
          url: string | null
          user_id: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          message: string
          request_id?: string | null
          status?: string
          type: string
          url?: string | null
          user_id?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          message?: string
          request_id?: string | null
          status?: string
          type?: string
          url?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      marketing_campaigns: {
        Row: {
          book_id: string
          caption: string | null
          channel: string
          created_at: string
          cta: string | null
          hashtags: string | null
          headline: string | null
          id: string
          language: string
          share_url: string | null
          status: string
          updated_at: string
        }
        Insert: {
          book_id: string
          caption?: string | null
          channel?: string
          created_at?: string
          cta?: string | null
          hashtags?: string | null
          headline?: string | null
          id?: string
          language?: string
          share_url?: string | null
          status?: string
          updated_at?: string
        }
        Update: {
          book_id?: string
          caption?: string | null
          channel?: string
          created_at?: string
          cta?: string | null
          hashtags?: string | null
          headline?: string | null
          id?: string
          language?: string
          share_url?: string | null
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "marketing_campaigns_book_id_fkey"
            columns: ["book_id"]
            isOneToOne: false
            referencedRelation: "books"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          bio: string | null
          created_at: string | null
          display_name: string | null
          is_public: boolean
          preferences: Json | null
          role: string | null
          updated_at: string | null
          user_id: string
          username: string | null
        }
        Insert: {
          avatar_url?: string | null
          bio?: string | null
          created_at?: string | null
          display_name?: string | null
          is_public?: boolean
          preferences?: Json | null
          role?: string | null
          updated_at?: string | null
          user_id: string
          username?: string | null
        }
        Update: {
          avatar_url?: string | null
          bio?: string | null
          created_at?: string | null
          display_name?: string | null
          is_public?: boolean
          preferences?: Json | null
          role?: string | null
          updated_at?: string | null
          user_id?: string
          username?: string | null
        }
        Relationships: []
      }
      reader_waitlist: {
        Row: {
          created_at: string
          email: string
          follow_author: string | null
          id: string
          invited_at: string | null
          priority: number
          source: string | null
          status: string
          wave_key: string | null
        }
        Insert: {
          created_at?: string
          email: string
          follow_author?: string | null
          id?: string
          invited_at?: string | null
          priority?: number
          source?: string | null
          status?: string
          wave_key?: string | null
        }
        Update: {
          created_at?: string
          email?: string
          follow_author?: string | null
          id?: string
          invited_at?: string | null
          priority?: number
          source?: string | null
          status?: string
          wave_key?: string | null
        }
        Relationships: []
      }
      readings: {
        Row: {
          book_id: string
          chapter_id: string | null
          current_chapter: number
          id: string
          last_read_at: string
          progress_percent: number
          started_at: string
          user_id: string
        }
        Insert: {
          book_id: string
          chapter_id?: string | null
          current_chapter?: number
          id: string
          last_read_at?: string
          progress_percent?: number
          started_at?: string
          user_id: string
        }
        Update: {
          book_id?: string
          chapter_id?: string | null
          current_chapter?: number
          id?: string
          last_read_at?: string
          progress_percent?: number
          started_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "readings_book_id_fkey"
            columns: ["book_id"]
            isOneToOne: false
            referencedRelation: "books"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "readings_chapter_id_fkey"
            columns: ["chapter_id"]
            isOneToOne: false
            referencedRelation: "chapters"
            referencedColumns: ["id"]
          },
        ]
      }
      reviews: {
        Row: {
          book_id: string
          content: string | null
          created_at: string
          id: string
          rating: number
          updated_at: string
          user_id: string
        }
        Insert: {
          book_id: string
          content?: string | null
          created_at?: string
          id: string
          rating: number
          updated_at?: string
          user_id: string
        }
        Update: {
          book_id?: string
          content?: string | null
          created_at?: string
          id?: string
          rating?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "reviews_book_id_fkey"
            columns: ["book_id"]
            isOneToOne: false
            referencedRelation: "books"
            referencedColumns: ["id"]
          },
        ]
      }
      shelf_books: {
        Row: {
          book_id: string
          created_at: string
          id: string
          section_id: string | null
          shelf_id: string
          sort_index: number
          updated_at: string
        }
        Insert: {
          book_id: string
          created_at?: string
          id?: string
          section_id?: string | null
          shelf_id: string
          sort_index?: number
          updated_at?: string
        }
        Update: {
          book_id?: string
          created_at?: string
          id?: string
          section_id?: string | null
          shelf_id?: string
          sort_index?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "shelf_books_book_id_fkey"
            columns: ["book_id"]
            isOneToOne: false
            referencedRelation: "books"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "shelf_books_section_id_fkey"
            columns: ["section_id"]
            isOneToOne: false
            referencedRelation: "shelf_sections"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "shelf_books_shelf_id_fkey"
            columns: ["shelf_id"]
            isOneToOne: false
            referencedRelation: "shelves"
            referencedColumns: ["id"]
          },
        ]
      }
      shelf_sections: {
        Row: {
          created_at: string
          id: string
          name: string
          shelf_id: string
          sort_index: number
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          shelf_id: string
          sort_index?: number
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          shelf_id?: string
          sort_index?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "shelf_sections_shelf_id_fkey"
            columns: ["shelf_id"]
            isOneToOne: false
            referencedRelation: "shelves"
            referencedColumns: ["id"]
          },
        ]
      }
      shelves: {
        Row: {
          cover_gradient: string | null
          cover_type: string | null
          cover_url: string | null
          created_at: string | null
          id: string
          name: string
          sort_index: number
          subtitle: string | null
          typography: Json | null
          updated_at: string
          user_id: string | null
        }
        Insert: {
          cover_gradient?: string | null
          cover_type?: string | null
          cover_url?: string | null
          created_at?: string | null
          id?: string
          name: string
          sort_index?: number
          subtitle?: string | null
          typography?: Json | null
          updated_at?: string
          user_id?: string | null
        }
        Update: {
          cover_gradient?: string | null
          cover_type?: string | null
          cover_url?: string | null
          created_at?: string | null
          id?: string
          name?: string
          sort_index?: number
          subtitle?: string | null
          typography?: Json | null
          updated_at?: string
          user_id?: string | null
        }
        Relationships: []
      }
      translations: {
        Row: {
          created_at: string
          id: string
          original_book_id: string
          status: string
          target_language: string
          translated_book_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          original_book_id: string
          status?: string
          target_language: string
          translated_book_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          original_book_id?: string
          status?: string
          target_language?: string
          translated_book_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "translations_original_book_id_fkey"
            columns: ["original_book_id"]
            isOneToOne: false
            referencedRelation: "books"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "translations_translated_book_id_fkey"
            columns: ["translated_book_id"]
            isOneToOne: true
            referencedRelation: "books"
            referencedColumns: ["id"]
          },
        ]
      }
      usage_counters: {
        Row: {
          count: number
          day: string
          key: string
          updated_at: string
          user_id: string
        }
        Insert: {
          count?: number
          day: string
          key: string
          updated_at?: string
          user_id: string
        }
        Update: {
          count?: number
          day?: string
          key?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      user_activity: {
        Row: {
          active_days_30: number
          first_seen_at: string
          last_event_at: string
          last_seen_at: string
          sessions_30: number
          state: string
          updated_at: string
          user_id: string
        }
        Insert: {
          active_days_30?: number
          first_seen_at?: string
          last_event_at?: string
          last_seen_at?: string
          sessions_30?: number
          state?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          active_days_30?: number
          first_seen_at?: string
          last_event_at?: string
          last_seen_at?: string
          sessions_30?: number
          state?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      user_flags: {
        Row: {
          beta_enabled: boolean
          created_at: string
          user_id: string
        }
        Insert: {
          beta_enabled?: boolean
          created_at?: string
          user_id: string
        }
        Update: {
          beta_enabled?: boolean
          created_at?: string
          user_id?: string
        }
        Relationships: []
      }
      waitlist: {
        Row: {
          created_at: string | null
          email: string
          id: string
          role: string | null
          source: string | null
        }
        Insert: {
          created_at?: string | null
          email: string
          id?: string
          role?: string | null
          source?: string | null
        }
        Update: {
          created_at?: string | null
          email?: string
          id?: string
          role?: string | null
          source?: string | null
        }
        Relationships: []
      }
      webhook_events: {
        Row: {
          id: string
          received_at: string
        }
        Insert: {
          id: string
          received_at?: string
        }
        Update: {
          id?: string
          received_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      user_entitlements: {
        Row: {
          is_pro: boolean | null
          user_id: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      book_status: "DRAFT" | "PUBLISHED" | "ARCHIVED"
      user_role: "reader" | "writer" | "ADMIN"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

<<<<<<< HEAD
type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      book_status: ["DRAFT", "PUBLISHED", "ARCHIVED"],
      user_role: ["reader", "writer", "ADMIN"],
    },
  },
} as const

// Convenience type exports
export type User = Database['public']['Tables']['users']['Row']
export type Profile = Database['public']['Tables']['profiles']['Row']
export type Book = Database['public']['Tables']['books']['Row']
export type Chapter = Database['public']['Tables']['chapters']['Row']
export type Shelf = Database['public']['Tables']['shelves']['Row']
export type ShelfSection = Database['public']['Tables']['shelf_sections']['Row']
export type ShelfBook = Database['public']['Tables']['shelf_books']['Row']
