import { NextResponse } from "next/server";

// ─── Error key constants ─────────────────────────────────────────────────────
// All API error responses MUST use these keys instead of user-facing text.
// The UI maps keys to localized messages via src/lib/error-messages.ts.

// Common
export const E_UNAUTHORIZED = "UNAUTHORIZED";
export const E_FORBIDDEN = "FORBIDDEN";
export const E_NOT_AUTHENTICATED = "NOT_AUTHENTICATED";
export const E_INVALID_JSON = "INVALID_JSON";
export const E_INVALID_REQUEST_BODY = "INVALID_REQUEST_BODY";
export const E_DATABASE_ERROR = "DATABASE_ERROR";
export const E_GENERIC_ERROR = "GENERIC_ERROR";
export const E_VALIDATION_FAILED = "VALIDATION_FAILED";

// Books
export const E_BOOK_NOT_FOUND = "BOOK_NOT_FOUND";
export const E_BOOK_SETTINGS_LOAD_FAILED = "BOOK_SETTINGS_LOAD_FAILED";
export const E_BOOK_SETTINGS_UPDATE_FAILED = "BOOK_SETTINGS_UPDATE_FAILED";
export const E_INVALID_BOOK_PRICING = "INVALID_BOOK_PRICING";
export const E_BOOK_CREATION_INCOMPLETE = "BOOK_CREATION_INCOMPLETE";
export const E_VERSION_CREATION_FAILED = "VERSION_CREATION_FAILED";
export const E_DEFAULT_CHAPTER_CREATION_FAILED = "DEFAULT_CHAPTER_CREATION_FAILED";

// Publishing
export const E_NO_BOOK_VERSION_TO_PUBLISH = "NO_BOOK_VERSION_TO_PUBLISH";
export const E_INVALID_BOOK_VERSION = "INVALID_BOOK_VERSION";
export const E_MISSING_VISIBILITY_SETTING = "MISSING_VISIBILITY_SETTING";
export const E_MISSING_BOOK_TITLE = "MISSING_BOOK_TITLE";
export const E_NO_CHAPTERS = "NO_CHAPTERS";
export const E_CHAPTER_NEEDS_CONTENT = "CHAPTER_NEEDS_CONTENT";
export const E_MISSING_COVER_IMAGE = "MISSING_COVER_IMAGE";

// Audiobook
export const E_AUDIOBOOK_FEATURE_DISABLED = "AUDIOBOOK_FEATURE_DISABLED";
export const E_AUDIOBOOK_STATUS_UNAVAILABLE = "AUDIOBOOK_STATUS_UNAVAILABLE";
export const E_JOB_CREATION_FAILED = "JOB_CREATION_FAILED";
export const E_QUEUE_UNAVAILABLE = "QUEUE_UNAVAILABLE";
export const E_BOOK_VERSION_NOT_FOUND_FOR_LANGUAGE = "BOOK_VERSION_NOT_FOUND_FOR_LANGUAGE";
export const E_NO_CHAPTERS_FOR_VERSION = "NO_CHAPTERS_FOR_VERSION";

// Translation
export const E_TRANSLATION_FEATURE_DISABLED = "TRANSLATION_FEATURE_DISABLED";
export const E_INVALID_TARGET_LANGUAGE = "INVALID_TARGET_LANGUAGE";
export const E_NO_SOURCE_VERSION = "NO_SOURCE_VERSION";
export const E_INVALID_SOURCE_VERSION = "INVALID_SOURCE_VERSION";
export const E_SOURCE_LANGUAGE_MISSING = "SOURCE_LANGUAGE_MISSING";
export const E_SAME_SOURCE_TARGET_LANGUAGE = "SAME_SOURCE_TARGET_LANGUAGE";
export const E_VERSION_ALREADY_EXISTS = "VERSION_ALREADY_EXISTS";
export const E_TRANSLATION_SERVICE_UNAVAILABLE = "TRANSLATION_SERVICE_UNAVAILABLE";

// Import
export const E_INVALID_MULTIPART_BODY = "INVALID_MULTIPART_BODY";
export const E_MISSING_FILE = "MISSING_FILE";
export const E_INVALID_IMPORT_MODE = "INVALID_IMPORT_MODE";
export const E_IMPORT_RECORD_CREATION_FAILED = "IMPORT_RECORD_CREATION_FAILED";
export const E_IMPORT_FILE_STORAGE_FAILED = "IMPORT_FILE_STORAGE_FAILED";
export const E_IMPORT_NOT_FOUND = "IMPORT_NOT_FOUND";
export const E_IMPORT_NOT_FAILED = "IMPORT_NOT_FAILED";
export const E_IMPORT_MISSING_FILE_INFO = "IMPORT_MISSING_FILE_INFO";

// Purchase
export const E_AUTHOR_CANNOT_BUY_OWN_BOOK = "AUTHOR_CANNOT_BUY_OWN_BOOK";
export const E_BOOK_IS_FREE = "BOOK_IS_FREE";
export const E_ALREADY_UNLOCKED = "ALREADY_UNLOCKED";
export const E_CHECKOUT_START_FAILED = "CHECKOUT_START_FAILED";
export const E_CHECKOUT_SESSION_FAILED = "CHECKOUT_SESSION_FAILED";

// Billing
export const E_INVALID_BILLING_PLAN = "INVALID_BILLING_PLAN";
export const E_BILLING_CONFIG_MISSING = "BILLING_CONFIG_MISSING";
export const E_BILLING_CHECKOUT_FAILED = "BILLING_CHECKOUT_FAILED";
export const E_BILLING_PORTAL_FAILED = "BILLING_PORTAL_FAILED";
export const E_PRO_SUBSCRIPTION_REQUIRED = "PRO_SUBSCRIPTION_REQUIRED";
export const E_PLUS_SUBSCRIPTION_REQUIRED = "PLUS_SUBSCRIPTION_REQUIRED";
export const E_SUBSCRIPTION_PAST_DUE = "SUBSCRIPTION_PAST_DUE";

// Offline reading
export const E_OFFLINE_FEATURE_DISABLED = "OFFLINE_FEATURE_DISABLED";
export const E_OFFLINE_MANIFEST_LOAD_FAILED = "OFFLINE_MANIFEST_LOAD_FAILED";
export const E_OFFLINE_CHAPTER_LOAD_FAILED = "OFFLINE_CHAPTER_LOAD_FAILED";

// Jobs
export const E_JOB_FETCH_FAILED = "JOB_FETCH_FAILED";

// TTS
export const E_TTS_DISABLED = "TTS_DISABLED";
export const E_TTS_BUSY = "TTS_BUSY";
export const E_TTS_SYNTHESIS_FAILED = "TTS_SYNTHESIS_FAILED";
export const E_TTS_UNEXPECTED_ERROR = "TTS_UNEXPECTED_ERROR";
export const E_BUCKET_NOT_FOUND = "BUCKET_NOT_FOUND";
export const E_AUDIO_URL_GENERATION_FAILED = "AUDIO_URL_GENERATION_FAILED";
export const E_NO_TEXT_IN_CHAPTERS = "NO_TEXT_IN_CHAPTERS";
export const E_TTS_ENV_CONFIG_ERROR = "TTS_ENV_CONFIG_ERROR";

// Bookmarks
export const E_BOOKMARK_LOAD_FAILED = "BOOKMARK_LOAD_FAILED";
export const E_ALREADY_BOOKMARKED = "ALREADY_BOOKMARKED";
export const E_BOOKMARK_ADD_FAILED = "BOOKMARK_ADD_FAILED";
export const E_BOOKMARK_REMOVE_FAILED = "BOOKMARK_REMOVE_FAILED";
export const E_INVALID_BOOK_ID = "INVALID_BOOK_ID";

// Reviews
export const E_REVIEWS_LOAD_FAILED = "REVIEWS_LOAD_FAILED";
export const E_REVIEW_SUBMIT_FAILED = "REVIEW_SUBMIT_FAILED";
export const E_REVIEW_UPDATE_FAILED = "REVIEW_UPDATE_FAILED";
export const E_REVIEW_AGGREGATE_FAILED = "REVIEW_AGGREGATE_FAILED";
export const E_ALREADY_REVIEWED = "ALREADY_REVIEWED";
export const E_REVIEW_NOT_FOUND = "REVIEW_NOT_FOUND";

// Comments
export const E_COMMENT_LOAD_FAILED = "COMMENT_LOAD_FAILED";
export const E_COMMENT_CREATE_FAILED = "COMMENT_CREATE_FAILED";
export const E_COMMENT_DELETE_FAILED = "COMMENT_DELETE_FAILED";
export const E_COMMENT_NOT_FOUND = "COMMENT_NOT_FOUND";
export const E_INVALID_COMMENT_ID = "INVALID_COMMENT_ID";
export const E_COMMENT_PARENT_NOT_FOUND = "COMMENT_PARENT_NOT_FOUND";
export const E_COMMENT_THREAD_DEPTH_EXCEEDED = "COMMENT_THREAD_DEPTH_EXCEEDED";
export const E_COMMENT_PARENT_MISMATCH = "COMMENT_PARENT_MISMATCH";
export const E_INVALID_CHAPTER_ID = "INVALID_CHAPTER_ID";

// Follows
export const E_FOLLOW_LIST_FAILED = "FOLLOW_LIST_FAILED";
export const E_FOLLOW_CREATE_FAILED = "FOLLOW_CREATE_FAILED";
export const E_FOLLOW_REMOVE_FAILED = "FOLLOW_REMOVE_FAILED";
export const E_INVALID_FOLLOWEE_ID = "INVALID_FOLLOWEE_ID";
export const E_CANNOT_FOLLOW_SELF = "CANNOT_FOLLOW_SELF";
export const E_ALREADY_FOLLOWING = "ALREADY_FOLLOWING";

// Direct messages
export const E_MESSAGE_LIST_FAILED = "MESSAGE_LIST_FAILED";
export const E_MESSAGE_CONVERSATION_CREATE_FAILED = "MESSAGE_CONVERSATION_CREATE_FAILED";
export const E_MESSAGE_SEND_FAILED = "MESSAGE_SEND_FAILED";
export const E_MESSAGE_CONVERSATION_NOT_FOUND = "MESSAGE_CONVERSATION_NOT_FOUND";
export const E_MESSAGE_REQUEST_ACCEPT_FAILED = "MESSAGE_REQUEST_ACCEPT_FAILED";
export const E_MESSAGE_BLOCK_FAILED = "MESSAGE_BLOCK_FAILED";
export const E_MESSAGE_BLOCKED = "MESSAGE_BLOCKED";
export const E_MESSAGE_INVALID_RECIPIENT = "MESSAGE_INVALID_RECIPIENT";

// Feedback
export const E_FEEDBACK_LOAD_FAILED = "FEEDBACK_LOAD_FAILED";
export const E_FEEDBACK_SAVE_FAILED = "FEEDBACK_SAVE_FAILED";

// Auth
export const E_INVALID_ROLE = "INVALID_ROLE";

// Marketing
export const E_MARKETING_FEATURE_DISABLED = "MARKETING_FEATURE_DISABLED";

// Waitlist
export const E_SERVER_CONFIG_ERROR = "SERVER_CONFIG_ERROR";
export const E_RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED";
export const E_INVALID_EMAIL = "INVALID_EMAIL";
export const E_SIGNUP_VERIFICATION_FAILED = "SIGNUP_VERIFICATION_FAILED";
export const E_WAITLIST_ADD_FAILED = "WAITLIST_ADD_FAILED";

// Admin
export const E_APPLICATIONS_LOAD_FAILED = "APPLICATIONS_LOAD_FAILED";
export const E_USER_ID_REQUIRED = "USER_ID_REQUIRED";
export const E_INVALID_STATUS_VALUE = "INVALID_STATUS_VALUE";
export const E_APPLICATION_UPDATE_FAILED = "APPLICATION_UPDATE_FAILED";
export const E_APPLICATION_SUBMIT_FAILED = "APPLICATION_SUBMIT_FAILED";
export const E_APPLICATION_CREATION_FAILED = "APPLICATION_CREATION_FAILED";
export const E_FUNNEL_DATA_LOAD_FAILED = "FUNNEL_DATA_LOAD_FAILED";

// AI
export const E_PROMPT_TEXT_REQUIRED = "PROMPT_TEXT_REQUIRED";
export const E_TEXT_TO_VIDEO_FAILED = "TEXT_TO_VIDEO_FAILED";
export const E_CONTENT_GENERATION_FAILED = "CONTENT_GENERATION_FAILED";
export const E_CONTENT_INVALID_CHANNEL_TYPE = "CONTENT_INVALID_CHANNEL_TYPE";
export const E_CONTENT_FETCH_FAILED = "CONTENT_FETCH_FAILED";

// Dev
export const E_NOT_AVAILABLE_IN_PRODUCTION = "NOT_AVAILABLE_IN_PRODUCTION";

// Credits
export const E_CREDITS_LOAD_FAILED = "CREDITS_LOAD_FAILED";

// Donation
export const E_DONATION_CHECKOUT_FAILED = "DONATION_CHECKOUT_FAILED";
export const E_INVALID_DONATION_AMOUNT = "INVALID_DONATION_AMOUNT";

// Referrals
export const E_REFERRAL_GENERATE_FAILED = "REFERRAL_GENERATE_FAILED";
export const E_REFERRAL_REDEEM_FAILED = "REFERRAL_REDEEM_FAILED";
export const E_REFERRAL_CODE_INVALID = "REFERRAL_CODE_INVALID";
export const E_REFERRAL_ALREADY_REDEEMED = "REFERRAL_ALREADY_REDEEMED";
export const E_REFERRAL_CANNOT_USE_OWN = "REFERRAL_CANNOT_USE_OWN";
export const E_INVALID_REFERRAL_CODE = "INVALID_REFERRAL_CODE";

// Pricing validation
export const E_INVALID_PRICE_AMOUNT = "INVALID_PRICE_AMOUNT";
export const E_INVALID_PRICE_CURRENCY = "INVALID_PRICE_CURRENCY";
export const E_INVALID_PRICING_MODEL = "INVALID_PRICING_MODEL";
export const E_INVALID_IS_FREE = "INVALID_IS_FREE";
export const E_INVALID_PRICING_COMBINATION = "INVALID_PRICING_COMBINATION";
export const E_NO_UPDATABLE_FIELDS = "NO_UPDATABLE_FIELDS";
export const E_PAID_BOOK_REQUIRES_CURRENCY = "PAID_BOOK_REQUIRES_CURRENCY";

// ─── Helper ──────────────────────────────────────────────────────────────────

/**
 * Return a JSON error response with a machine-readable error key.
 * Never pass user-facing text — the UI resolves keys to localized messages.
 *
 * @param key   One of the E_* constants above
 * @param status HTTP status code
 * @param extra  Optional extra fields merged into the JSON body (e.g. { detail })
 */
export function apiError(
  key: string,
  status: number,
  extra?: Record<string, unknown>
): NextResponse {
  return NextResponse.json({ error: key, ...extra }, { status });
}
